export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={
          {
            background: 'brown',
            color: 'white',
            padding: '1rem',
            textAlign: 'center',
          }
        }
        >
          <p>Header</p>
        </header>
        {children}</body>
        <footer
        style={
          {
            background: 'blue',
            color: 'white',
            padding: '1rem',
            textAlign: 'center',
        }}
        >
          <p>Footer</p>
        </footer>
    </html>
  )
}
